on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          
      # The following steps run only if a release was created
      - uses: actions/checkout@v4
        if: ${{ steps.release-please.outputs.release_created }}
        
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release-please.outputs.release_created }}
        
      - run: npm ci
        if: ${{ steps.release-please.outputs.release_created }}
        
      - run: npm run build
        if: ${{ steps.release-please.outputs.release_created }}
        
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release-please.outputs.release_created }}
          